# Generated by Django 5.1.4 on 2024-12-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_user1_remove_chat_user1_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuser',
            name='is_read',
        ),
        migrations.AddField(
            model_name='chatuser',
            name='has_new_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
