# Generated by Django 5.1.4 on 2025-01-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user_1_has_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='user_2_has_read',
            field=models.BooleanField(default=False),
        ),
    ]
