# Generated by Django 5.1.4 on 2025-01-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_communitymessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
