# Generated by Django 5.1.4 on 2024-12-24 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_person_delete_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(blank=True, null=True)),
                ('media1', models.FileField(blank=True, null=True, upload_to='medias/')),
                ('media2', models.FileField(blank=True, null=True, upload_to='medias/')),
                ('media3', models.FileField(blank=True, null=True, upload_to='medias/')),
                ('media4', models.FileField(blank=True, null=True, upload_to='medias/')),
                ('likes', models.BigIntegerField()),
                ('frowns', models.BigIntegerField()),
                ('ghost_likes', models.BigIntegerField()),
                ('comments', models.BigIntegerField()),
                ('shares', models.BigIntegerField()),
                ('interactions', models.BigIntegerField()),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
