# Generated by Django 5.1.4 on 2024-12-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='frowns',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='ghost_likes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='interactions',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='shares',
            field=models.BigIntegerField(default=0),
        ),
    ]
