# Generated by Django 5.1.4 on 2024-12-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_post_comments_alter_post_frowns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='pfp/'),
        ),
    ]
