# Generated by Django 5.1.4 on 2024-12-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_person_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
