# Generated by Django 5.1.4 on 2024-12-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_personcommunity_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='isPrivate',
            new_name='is_private',
        ),
    ]
