# Generated by Django 5.1.4 on 2024-12-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_isprivate_community_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='long',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
