# Generated by Django 5.1.4 on 2024-12-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_person_lat_person_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='lat',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
