# Generated by Django 5.1.4 on 2024-12-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_notification_id_item_notification_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
        migrations.AddField(
            model_name='notification',
            name='id_item',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
