# Generated by Django 5.1.4 on 2024-12-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_joinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id_item',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
