# Generated by Django 5.1.4 on 2025-01-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
