# Generated by Django 5.1.4 on 2025-01-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_community_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isPrivate',
            field=models.BooleanField(default=True),
        ),
    ]
