# Generated by Django 5.1.4 on 2025-01-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_person_has_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='has_notification',
        ),
    ]
