# Generated by Django 5.1.4 on 2025-01-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_remove_person_has_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='community_pfp/'),
        ),
    ]
