# Generated by Django 5.1.4 on 2025-01-19 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_ban'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fans',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='obsessions',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='stalkers',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('FO', 'Fan'), ('ST', 'Stalk'), ('NO', 'None')], default='NO', max_length=10)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
