# Generated by Django 5.1.4 on 2025-01-19 14:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_person_fans_person_obsessions_person_stalkers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relationships',
            new_name='Relationship',
        ),
    ]
