# Generated by Django 5.1.4 on 2025-01-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_alter_relationship_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='freq',
            field=models.IntegerField(default=0),
        ),
    ]
